def query_llm(texts:str):
    """
    Input: texts in first 10 pages
    Output: tags generated by LLM, formatted as a List
    """
    # ##############################################################################
    # #                  TODO: You need to complete the code here                  #
    # ##############################################################################
    import os
    Full = "Give me some(about 10-20) tags based on the context below, without any other things!\n"+texts
    with open('Query.txt', 'w') as f:
        f.write(Full)
    os.system("/share/ollama/ollama run llama3:70b < Query.txt > Query.tag")
    texts = []
    with open('Query.tag', 'r') as f:
        lines = f.readlines()
        for line in lines:
            # check if it starts with a number
            if line[0].isdigit():
                items = line.split(' ')[1:]
                string = ''
                for item in items:
                    string += item + ' '
                texts.append(string.replace('\n', '').replace('*','').replace('#','').replace('\'','').replace('\"','')[:-1])
    # ##############################################################################
    # #                              END OF YOUR CODE                              #
    # ##############################################################################
    return texts[100:200] if len(texts)>200 else texts
if __name__ == '__main__':
    string = '''一是定态问题(stationary state problem)的求解'''
    print(query_llm(string))
    exit(0)